# Generated by Django 6.0.6 on 2026-06-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Korxona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=255, verbose_name='Korxona nomi')),
                ('inn', models.CharField(max_length=20, unique=True, verbose_name='INN')),
                ('manzil', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('rahbar', models.CharField(blank=True, max_length=255, verbose_name='Rahbar')),
                ('telefon', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Korxona',
                'verbose_name_plural': 'Korxonalar',
                'ordering': ['nomi'],
            },
        ),
    ]
