# Generated by Django 6.0.6 on 2026-06-17 10:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('korxonalar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MahsulotTuri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tartib_raqam', models.PositiveSmallIntegerField(unique=True, verbose_name='T/p')),
                ('nomi', models.CharField(max_length=200, verbose_name='Mahsulot nomi')),
                ('qabul_mavjud', models.BooleanField(default=True, verbose_name='Qabul qilingan ustuni mavjud')),
                ('sarflangan_mavjud', models.BooleanField(default=True, verbose_name='Ishlab chiqarishga sarflangan ustuni mavjud')),
                ('ishlab_chiqarish_mavjud', models.BooleanField(default=True, verbose_name='Ishlab chiqarish ustuni mavjud')),
                ('realizatsiya_mavjud', models.BooleanField(default=True, verbose_name='Realizatsiya ustuni mavjud')),
                ('eksport_mavjud', models.BooleanField(default=True, verbose_name='Eksport ustuni mavjud')),
            ],
            options={
                'verbose_name': 'Mahsulot turi',
                'verbose_name_plural': 'Mahsulot turlari',
                'ordering': ['tartib_raqam'],
            },
        ),
        migrations.CreateModel(
            name='OylikHisobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)], verbose_name='Yil')),
                ('oy', models.PositiveSmallIntegerField(choices=[(1, 'Yanvar'), (2, 'Fevral'), (3, 'Mart'), (4, 'Aprel'), (5, 'May'), (6, 'Iyun'), (7, 'Iyul'), (8, 'Avgust'), (9, 'Sentabr'), (10, 'Oktabr'), (11, 'Noyabr'), (12, 'Dekabr')], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Oy')),
                ('yaratilgan', models.DateTimeField(auto_now_add=True)),
                ('yangilangan', models.DateTimeField(auto_now=True)),
                ('korxona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hisobotlar', to='korxonalar.korxona', verbose_name='Korxona')),
            ],
            options={
                'verbose_name': 'Oylik hisobot',
                'verbose_name_plural': 'Oylik hisobotlar',
                'ordering': ['-yil', '-oy'],
                'unique_together': {('korxona', 'yil', 'oy')},
            },
        ),
        migrations.CreateModel(
            name='HisobotQatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yil_boshi_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Yil boshi qoldiq (hajmi, dal)')),
                ('yil_boshi_absolyut', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Yil boshi qoldiq (absolyut spirt, dal)')),
                ('qabul_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Qabul qilingan (dal)')),
                ('sarflangan_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Ishlab chiqarishga sarflangan (dal)')),
                ('ishlab_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Ishlab chiqarish (hajmi, dal)')),
                ('ishlab_absolyut', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Ishlab chiqarish (absolyut spirt, dal)')),
                ('realizatsiya_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Realizatsiya (hajmi, dal)')),
                ('realizatsiya_absolyut', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Realizatsiya (absolyut spirt, dal)')),
                ('realizatsiya_summasi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="Realizatsiya (summasi, so'm)")),
                ('eksport_absolyut', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Eksport (absolyut spirt, dal)')),
                ('eksport_summasi', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name="Eksport (summasi, so'm)")),
                ('yoqotish_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name="Yo'qotishlar (dal)")),
                ('oz_ehtiyoj_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name="O'z ehtiyoji uchun (dal)")),
                ('oy_oxiri_hajmi', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Oy oxiri qoldiq (hajmi, dal)')),
                ('oy_oxiri_absolyut', models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Oy oxiri qoldiq (absolyut spirt, dal)')),
                ('mahsulot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qatorlar', to='hisobotlar.mahsulotturi', verbose_name='Mahsulot turi')),
                ('hisobot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='hisobotlar.oylikhisobot', verbose_name='Hisobot')),
            ],
            options={
                'verbose_name': 'Hisobot qatori',
                'verbose_name_plural': 'Hisobot qatorlari',
                'ordering': ['mahsulot__tartib_raqam'],
                'unique_together': {('hisobot', 'mahsulot')},
            },
        ),
    ]
