# Generated by Django 6.0.6 on 2026-06-17 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hisobotlar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hisobotqatori',
            name='eksport_hajmi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=15, null=True, verbose_name='Eksport (hajmi, dal)'),
        ),
    ]
